version: "3.8"

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    volumes:
      - static_data:/app/result_build

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    depends_on:
      - backend
      - frontend
